#!/bin/bash
version=$1
echo Erzeugee Version $version
cp ../target/JanusAngular2.backend-0.0.1-SNAPSHOT.jar ../docker/app.jar
cd ../docker
docker build --tag=thonill/janusangular2:$version .
cd ../dockersh
